version: '{build}'
skip_non_tags: true
image: Visual Studio 2019
clone_depth: 1
init:
- ps: git config --global core.autocrlf true
environment:
  MODULE_NAME: luaerror
  REPOSITORY_DIR: $(APPVEYOR_BUILD_FOLDER)
  DEPENDENCIES: $(APPVEYOR_BUILD_FOLDER)/dependencies
  GARRYSMOD_COMMON: $(APPVEYOR_BUILD_FOLDER)/dependencies/garrysmod_common
  GARRYSMOD_COMMON_REPOSITORY: https://github.com/danielga/garrysmod_common.git
  GARRYSMOD_COMMON_BRANCH: master
  SOURCE_SDK: $(APPVEYOR_BUILD_FOLDER)/dependencies/sourcesdk-minimal
  SOURCE_SDK_REPOSITORY: https://github.com/danielga/sourcesdk-minimal.git
  SOURCE_SDK_BRANCH: master
  PREMAKE5_URL: https://github.com/premake/premake-core/releases/download/v5.0.0-alpha14/premake-5.0.0-alpha14-windows.zip
  PREMAKE5_EXECUTABLE: premake5.exe
  PREMAKE5: $(APPVEYOR_BUILD_FOLDER)/dependencies/windows/premake-core/premake5.exe
  BUILD_SCRIPT: $(APPVEYOR_BUILD_FOLDER)/dependencies/garrysmod_common/build/build.ps1
  BOOTSTRAP_URL: https://raw.githubusercontent.com/danielga/garrysmod_common/master/build/bootstrap.ps1
  PROJECT_OS: windows
  TARGET_OS: win32
  TARGET_OS_64: win64
  TARGET_ARCHITECTURE: x86
  TARGET_ARCHITECTURE_64: x86_64
  PROJECT_GENERATOR_VERSION: 2
  COMPILER_PLATFORM: vs2019
  DISABLE_X86_64_BUILD: true
install:
- ps: 'Invoke-Expression ((New-Object System.Net.WebClient).DownloadString("$env:BOOTSTRAP_URL"))'
build_script:
- ps: '& "$env:BUILD_SCRIPT"'
test: off
artifacts:
- path: projects/$(PROJECT_OS)/$(COMPILER_PLATFORM)/$(TARGET_ARCHITECTURE)/Release/gmsv_$(MODULE_NAME)_$(TARGET_OS).dll
  name: gmsv_$(MODULE_NAME)_$(TARGET_OS).dll
- path: projects/$(PROJECT_OS)/$(COMPILER_PLATFORM)/$(TARGET_ARCHITECTURE)/Release/gmcl_$(MODULE_NAME)_$(TARGET_OS).dll
  name: gmcl_$(MODULE_NAME)_$(TARGET_OS).dll
- path: projects/$(PROJECT_OS)/$(COMPILER_PLATFORM)/$(TARGET_ARCHITECTURE_64)/Release/gmsv_$(MODULE_NAME)_$(TARGET_OS_64).dll
  name: gmsv_$(MODULE_NAME)_$(TARGET_OS_64).dll
- path: projects/$(PROJECT_OS)/$(COMPILER_PLATFORM)/$(TARGET_ARCHITECTURE_64)/Release/gmcl_$(MODULE_NAME)_$(TARGET_OS_64).dll
  name: gmcl_$(MODULE_NAME)_$(TARGET_OS_64).dll
deploy:
- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  auth_token:
    secure: RUV3yI/I+UVyAYizK5dWfGU95IZwbKr3g4RPqeGFvlPnQAxTGp4Kt5yZhXylRxSS
  artifact: gmsv_$(MODULE_NAME)_$(TARGET_OS).dll,gmcl_$(MODULE_NAME)_$(TARGET_OS).dll,gmsv_$(MODULE_NAME)_$(TARGET_OS_64).dll,gmcl_$(MODULE_NAME)_$(TARGET_OS_64).dll
  force_update: true
