language: cpp
if: tag IS present
env:
  global:
    - MODULE_NAME=luaerror
      REPOSITORY_DIR="$TRAVIS_BUILD_DIR"
      DEPENDENCIES="$TRAVIS_BUILD_DIR/dependencies"
      GARRYSMOD_COMMON="$TRAVIS_BUILD_DIR/dependencies/garrysmod_common"
      SOURCE_SDK="$TRAVIS_BUILD_DIR/dependencies/sourcesdk-minimal"
      TARGET_OS="$TRAVIS_OS_NAME"
      COMPILER_PLATFORM=gmake
      BUILD_SCRIPT="$TRAVIS_BUILD_DIR/dependencies/garrysmod_common/build/ci.sh"
      GARRYSMOD_COMMON_REPOSITORY="https://github.com/danielga/garrysmod_common.git"
      PREMAKE5_EXECUTABLE=premake5
matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - linux-libc-dev:i386
            - g++-8-multilib
      env:
        - PREMAKE5="$TRAVIS_BUILD_DIR/dependencies/linux/premake-core/premake5"
          PROJECT_OS=linux
      before_install:
        - export CC=gcc-8
          export CXX=g++-8
    - os: osx
      osx_image: xcode9.4
      env:
        - PREMAKE5="$TRAVIS_BUILD_DIR/dependencies/macosx/premake-core/premake5"
          PROJECT_OS=macosx
cache:
  directories:
    - "$TRAVIS_BUILD_DIR/dependencies"
    - "$TRAVIS_BUILD_DIR/projects"
install:
  - mkdir -p "$DEPENDENCIES"
  - if [ ! -f "$GARRYSMOD_COMMON/premake5.lua" ]; then
      echo "garrysmod_common directory is empty, doing git clone of the remote repo";
      git clone --recursive "$GARRYSMOD_COMMON_REPOSITORY" "$GARRYSMOD_COMMON";
    else
      echo "garrysmod_common directory is good, pulling any latest changes";
      git -C "$GARRYSMOD_COMMON" pull;
      git -C "$GARRYSMOD_COMMON" submodule update --init --recursive;
    fi
script: "$BUILD_SCRIPT"
deploy:
  provider: releases
  skip_cleanup: true
  file:
    - "${TRAVIS_BUILD_DIR}/projects/${PROJECT_OS}/${COMPILER_PLATFORM}/release/gmsv_${MODULE_NAME}_${TARGET_OS}.dll"
    - "${TRAVIS_BUILD_DIR}/projects/${PROJECT_OS}/${COMPILER_PLATFORM}/release/gmcl_${MODULE_NAME}_${TARGET_OS}.dll"
  on:
    tags: true
  api_key:
    secure: W9DotAUb068MYIUp3lbvxcdZTglYwNQIAIJjzj6KWL4lz4rZdNV31ZsvvMmyUew10enNAY0GJfKEkWFB38ljVSokJbvJIvqjSCdzTRHYUew7gAFRC51yQ+kuH1zXhaqfp8BZrg7Z+aYXzXaIZ09P/y06grybbJ5RUq5k8G1ZiVUe52kP3GqevI47A4rrbpmvuwTDuW1ldCIxd/M2BwbXRTwrTgKg9PKvwKQXoa5VLMulajJXBeN3+x3LhzyB/Rz01XuQm5GqOLRxxkTL7CEnYmT4gymglR0ApzNfXa7FFCgF3KeV/y7rdCR4OrIaKC7BdjpRTFEaDVqaJzti9GgwtnbAG34FoYUd7twIhbILynmhM6z/QH5zPe4/hmM2doga+vEz34MK4+ogY4fL0+KOt3Ye/KB+oGU1LUKgzmJ9XvREY5MCw+CtNJUrVS/WIYWCe8AkA1IgAOd6xMyLtag8OunLXMHWJSeJ4i+ufzv0bQ1Ml2Ddn3NrdRi+p8mtr5kp+ecR6trQovYdtYnBwk4G8TYxLr8ZotP6Z4qrppH++r8maxqTF5FNLnkshhuCFGWCayn9V72AYiFXDWuXRfONvE6hcWftDe+zOXm5UpQ/qfb/QoyiaYVl6Ir3003qUriAenFoKDgrc7byAU1SB64jyDNqXcsk7ge/DAiAKmv6u7s=
