language: cpp
if: tag IS present
git:
  depth: 1
env:
  global:
    - MODULE_NAME=luaerror
      REPOSITORY_DIR="$TRAVIS_BUILD_DIR"
      DEPENDENCIES="$TRAVIS_BUILD_DIR/dependencies"
      GARRYSMOD_COMMON="$TRAVIS_BUILD_DIR/dependencies/garrysmod_common"
      GARRYSMOD_COMMON_REPOSITORY="https://github.com/danielga/garrysmod_common.git"
      GARRYSMOD_COMMON_BRANCH=master
      SOURCE_SDK="$TRAVIS_BUILD_DIR/dependencies/sourcesdk-minimal"
      SOURCE_SDK_REPOSITORY="https://github.com/danielga/sourcesdk-minimal.git"
      SOURCE_SDK_BRANCH=master
      PREMAKE5="$TRAVIS_BUILD_DIR/dependencies/windows/premake-core/premake5.exe"
      BUILD_SCRIPT="$TRAVIS_BUILD_DIR/dependencies/garrysmod_common/build/build.sh"
      BOOTSTRAP_URL="https://raw.githubusercontent.com/danielga/garrysmod_common/master/build/bootstrap.sh"
      TARGET_OS="$TRAVIS_OS_NAME"
      TARGET_OS_64="${TRAVIS_OS_NAME}64"
      TARGET_ARCHITECTURE=x86
      TARGET_ARCHITECTURE_64=x86_64
      PROJECT_GENERATOR_VERSION=2
      COMPILER_PLATFORM=gmake
      DISABLE_X86_64_BUILD=true
matrix:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      addons:
        apt:
          packages:
            - linux-libc-dev:i386
            - g++-8-multilib
      env:
        - PREMAKE5="$TRAVIS_BUILD_DIR/dependencies/linux/premake-core/premake5"
          PROJECT_OS=linux
          PREMAKE5_URL="https://github.com/premake/premake-core/releases/download/v5.0.0-alpha14/premake-5.0.0-alpha14-linux.tar.gz"
      before_install:
        - export CC=gcc-8
          export CXX=g++-8
    - os: osx
      osx_image: xcode9.4
      env:
        - PREMAKE5="$TRAVIS_BUILD_DIR/dependencies/macosx/premake-core/premake5"
          PROJECT_OS=macosx
          PREMAKE5_URL="https://github.com/premake/premake-core/releases/download/v5.0.0-alpha14/premake-5.0.0-alpha14-macosx.tar.gz"
install: "curl -s -L \"$BOOTSTRAP_URL\" | bash"
script: "$BUILD_SCRIPT"
deploy:
  provider: releases
  skip_cleanup: true
  file:
    - "${TRAVIS_BUILD_DIR}/projects/${PROJECT_OS}/${COMPILER_PLATFORM}/${TARGET_ARCHITECTURE}/Release/gmsv_${MODULE_NAME}_${TARGET_OS}.dll"
    - "${TRAVIS_BUILD_DIR}/projects/${PROJECT_OS}/${COMPILER_PLATFORM}/${TARGET_ARCHITECTURE}/Release/gmcl_${MODULE_NAME}_${TARGET_OS}.dll"
    - "${TRAVIS_BUILD_DIR}/projects/${PROJECT_OS}/${COMPILER_PLATFORM}/${TARGET_ARCHITECTURE_64}/Release/gmsv_${MODULE_NAME}_${TARGET_OS_64}.dll"
    - "${TRAVIS_BUILD_DIR}/projects/${PROJECT_OS}/${COMPILER_PLATFORM}/${TARGET_ARCHITECTURE_64}/Release/gmcl_${MODULE_NAME}_${TARGET_OS_64}.dll"
  on:
    tags: true
  api_key:
    secure: IxRaO36ixoWZf6MK23XixRm4hAT8EtZNTEpZRfDXPSjIsD3LdwJw5D8/ezkKpQmrQiI+5BpA05D69vkfv0/q9zoiev1A+q6uldqrPVKEk7goGjWUk77Iw2nJsj1sEdGQQKAcCaJ7LCA6i9pHdbNg/3r4DkulMEDvwrv2Ip9YBnmzMsc5e6xjn1LR3cPq6X2f0A1QfAjKtnqj5Nk0QRTeE4Q4qpYZVvf9HMnjwxlAuxPpsi0QoOn0mjRYtYeuq6cfYZcp54E+DwJ+ZVv2RXLfZxDQMleE3wb5DoeEnK9d2n4wFDOB1/p04UsqlhzFdnyr81kwqM3lvJ202pQfMkhSwehZB7RQt5zPkRcLQrQ00orzQorkrMry8bTFxNQ3t6dRhio8ModPy+HmiNL+ena1VHXTXL3qUT9vM5HBN8tQ/Uwmc24jNxOGhy/rjnB+gvHV7UcXegI2T5MnXnblvshaxzXODRY5ZeK0RprESV0o8Wk872anxZQdb6krHuKgbQRURwrztAoK81VI+DnS/d6KpSFUyQPnqGtpfxT4aXhGNR/cgCMW0eDxGHBYEsLQ46fH+qAGlPe5WfQWRgq2sOqfG+BfKrtZx8IZ/MnACUSj1Pq6YHQ6l9nwMdYuPcfA1DSJxoQgghiK+ta9ADKvqhbdg6M6+hIyuObXkr2Bj3vdeaY=
