name: Build Module

on: 
  push:
    paths:
      - '.github/workflows/compile.yml'
      - 'source/**'
      - 'premake5.lua'
  pull_request:
  workflow_dispatch:

jobs:
  build_module_sv:
    name: "Build Module (Server)"
    uses: RaphaelIT7/gmod-common-module-base/.github/workflows/compile.yml@workflow
    with:
      PROJECT_NAME: "luaerror"
      BUILD_64x: "false"
      REALM: "sv"
      BUILD_WINDOWS: "true"
      ARTIFACT_EXPIRE: "7"

  build_module_cl:
    name: "Build Module (Client)"
    uses: RaphaelIT7/gmod-common-module-base/.github/workflows/compile.yml@workflow
    with:
      PROJECT_NAME: "luaerror"
      BUILD_64x: "false"
      REALM: "cl"
      BUILD_WINDOWS: "true"
      ARTIFACT_EXPIRE: "7"